version: '2'

services:
  source:
    image: redis
  target:
    image: redis
  migrate:
    build: .
    depends_on:
      - source
      - target
    volumes: 
      - ./compose:/migrate
    environment:
      - SOURCE
      - TARGET
      - COMMON
      - REPLICATION_GROUP
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY